export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";

export const GET_ALL_POST_REQUEST = "GET_ALL_POST_REQUEST";
export const GET_ALL_POST_SUCCESS = "GET_ALL_POST_SUCCESS";
export const GET_ALL_POST_FAILURE = "GET_ALL_POST_FAILURE";

export const GET_USERS_ALL_POST_REQUEST = "GET_USERS_ALL_POST_REQUEST";
export const GET_USERS_ALL_POST_SUCCESS = "GET_USERS_ALL_POST_SUCCESS";
export const GET_USERS_ALL_POST_FAILURE = "GET_USERS_ALL_POST_FAILURE";

export const GET_LIKED_POST_REQUEST = "GET_LIKED_POST_REQUEST";
export const GET_LIKED_POST_SUCCESS = "GET_LIKED_POST_SUCCESS";
export const GET_LIKED_POST_FAILURE = "GET_LIKED_POST_FAILURE";

export const LIKE_POST_REQUEST = "LIKE_POST_REQUEST";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_FAILURE = "LIKE_POST_FAILURE";

export const FIND_POST_BY_CONTENT_REQUEST = "FIND_POST_BY_CONTENT_REQUEST";
export const FIND_POST_BY_CONTENT_SUCCESS = "FIND_POST_BY_CONTENT_SUCCESS";
export const FIND_POST_BY_CONTENT_FAILURE = "FIND_POST_BY_CONTENT_FAILURE";

export const FIND_POST_BY_ID_REQUEST = "FIND_POST_BY_ID_REQUEST";
export const FIND_POST_BY_ID_SUCCESS = "FIND_POST_BY_ID_SUCCESS";
export const FIND_POST_BY_ID_FAILURE = "FIND_POST_BY_ID_FAILURE";

export const COMMENT_POST_REQUEST = "COMMENT_POST_REQUEST";
export const COMMENT_POST_SUCCESS = "COMMENT_POST_SUCCESS";
export const COMMENT_POST_FAILURE = "COMMENT_POST_FAILURE";

export const SUGGESTIONS_REQUEST = "SUGGESTIONS_REQUEST";
export const SUGGESTIONS_SUCCESS = "SUGGESTIONS_SUCCESS";
export const SUGGESTIONS_FAILURE = "SUGGESTIONS_FAILURE";

export const MEDIA_DELETE_REQUEST = "MEDIA_DELETE_REQUEST";
export const MEDIA_DELETE_SUCCESS = "MEDIA_DELETE_SUCCESS";
export const MEDIA_DELETE_FAILURE = "MEDIA_DELETE_FAILURE";

export const EDIT_POST_REQUEST = "EDIT_POST_REQUEST";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_FAILURE = "EDIT_POST_FAILURE";